### ISSUE TITLE
Wercker のビルド失敗

### ISSUE THREAD

**Issue by shuhei** [m3dev/m3dev.github.com#13]
https://app.wercker.com/#buildstep/553d869c41e60e965a08f1c7

**Comment by morizyun** [comment]
Thank you a lot! :+1:

**Comment by lloydmeta** [comment]
I manually triggered a webhook payload send and it seems to have worked this time. Closing for now.

**Comment by shuhei** [comment]
Thanks! I guess it was because Ruby 2.2.2 installation took long time at the first build.

**Comment by lloydmeta** [comment]
Ah good point.
